version: '2'
services:
  feedback-bot-run:
    container_name: feedback-bot-run
    build: .
    command: go run main.go
    volumes:
      - .:/go/src/app
    ports:
      - "3003:3000"
    environment:
      PORT: 3000
