version: '3.7'

services:
  feedback-bot-db:
    image: postgres:11.3-alpine
    restart: always
    ports:
      - ${DBPORT}:${DBPORT}
    environment:
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - feedback-bot-data:/var/lib/postgresql/data
  feedback-bot-server:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "feedback-bot-db:5432",
        "--",
        "go",
        "run",
        "main.go"
      ]
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DBHOST: feedback-bot-db
      DBPORT: ${DBPORT}
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      BOT_OAUTH_ACCESS_TOKEN: ${BOT_OAUTH_ACCESS_TOKEN}    
      VERIFICATION_TOKEN: ${VERIFICATION_TOKEN}
    depends_on:
      - feedback-bot-db

volumes:
  feedback-bot-data: